name: notes
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  
  authentication_repository:
    path: packages/authentication_repository
  local_notes_repository:
    path: packages/local_notes_repository
  firebase_notes_repository:
    path: packages/firebase_notes_repository
    
  animations: ^2.0.1
  bloc: ^7.2.0
  cloud_firestore: ^2.3.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  
  flow_builder: ^0.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_staggered_grid_view: ^0.4.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  localizely:
    project_id: 598a4465-a901-403c-8eca-eacac1347399
