name: authentication_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
environment:
  sdk: '>=2.15.0-15.0.dev <3.0.0'

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.3
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  google_sign_in: ^5.0.7
